version: "3.8"

services:
 wordpress:
   image: wordpress
   container_name: wordpress
   restart: always
   ports:
     - "8000:80"
   environment:
     WORDPRESS_DB_HOST: db
     WORDPRESS_DB_USER:  wordpress
     WORDPRESS_DB_PASSWORD: wordpress
     WORDPRESS_DB_NAME: wordpress
   volumes:
     - wordpress_data:/var/www/html

 db:
   image: mysql:5.7
   restart: always
   container_name: mysql
   environment:
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress
     MYSQL_ROOT_PASSWORD: wordpress
   volumes:
     - db_data:/var/lib/mysql

 cadvisor:
   image: gcr.io/cadvisor/cadvisor:latest
   restart: always
   container_name: cadvisor
   ports:
     - 9080:8080
   volumes:
     - "/:/rootfs"
     - "/var/run:/var/run"
     - "/sys:/sys"
     - "/var/lib/docker/:/var/lib/docker"
     - "/dev/disk/:/dev/disk"
   privileged: true
   devices:
       - /dev/kmsg

prometheus:
   image: prom/prometheus:latest
   restart: always
   container_name: prometheus
   ports:
     - 9090:9090
   volumes:
     - "./prometheus.yml:/etc/prometheus/prometheus.yml"
     - prometheusdata:/prometheus
   privileged: true
   depends_on:
     - cadvisor

 grafana:
   image: grafana/grafana-enterprise
   container_name: grafana
   restart: unless-stopped
   ports:
     - '4000:3000'
   volumes:
     - grafana-storage:/var/lib/grafana
   depends_on:
     - prometheus

 node-exporter:
   image: prom/node-exporter:latest
   container_name: node-exporter
   restart: unless-stopped
   volumes:
     - /proc:/host/proc:ro
     - /sys:/host/sys:ro
     - /:/rootfs:ro
   command:
     - '--path.procfs=/host/proc'
     - '--path.rootfs=/rootfs'
     - '--path.sysfs=/host/sys'
     - '--collector.filesystem.mount-points-exclude=^/(sys¦proc¦dev¦host¦etc) ($$¦/)'
   ports:
     - 9100:9100

volumes:
 wordpress_data:
 db_data:
 prometheusdata:
 grafana-storage: