global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["192.168.111.11:9080"]

  - job_name: "wordpress"
    static_configs:
      - targets: ["192.168.111.11:8000"]

  - job_name: "windows server"
    static_configs:
      - targets: ["192.168.111.10:9182"]

  - job_name: "node"
    static_configs:
      - targets: ["192.168.111.11:9100"]
